# Generated by Django 6.0.2 on 2026-03-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Název balíčku')),
                ('version', models.CharField(max_length=50, verbose_name='Verze')),
                ('slug', models.SlugField(help_text='Unikátní identifikátor (např. nazev-app-v1)', unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Popis balíčku')),
                ('archive_file', models.FileField(upload_to='packages/archives/', verbose_name='ZIP Archiv')),
                ('manifest_data', models.JSONField(blank=True, default=dict, verbose_name='Data z manifestu')),
                ('file_size', models.BigIntegerField(default=0, help_text='Velikost v bajtech')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publikováno')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Balíček',
                'verbose_name_plural': 'Balíčky',
                'ordering': ['-created_at'],
            },
        ),
    ]
