# Generated by Django 6.0.2 on 2026-03-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='version',
        ),
        migrations.AddField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('installer', 'Instalátor'), ('ready_to_play', 'Ready to Play'), ('patch', 'Patch / Fix'), ('other', 'Ostatní')], default='installer', max_length=20, verbose_name='Typ balíčku'),
        ),
        migrations.AlterField(
            model_name='package',
            name='archive_file',
            field=models.FileField(upload_to='archives/', verbose_name='ZIP Archiv'),
        ),
    ]
