# Generated by Django 6.0.2 on 2026-03-05 00:31

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_package_version_package_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='archive_file',
            field=models.FileField(upload_to=api.models.get_upload_path, validators=[api.models.validate_is_zip], verbose_name='ZIP Archiv'),
        ),
        migrations.AlterField(
            model_name='package',
            name='file_size',
            field=models.BigIntegerField(default=0, help_text='Velikost v bajtech — vyplňuje se automaticky z nahraného souboru.'),
        ),
    ]
