# Generated by Django 6.0.2 on 2026-03-07 16:35

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_populate_manifest_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='pending_filename',
            field=models.CharField(blank=True, help_text='Název ZIP souboru umístěného ve složce packages/new/ na serveru (např. hra.zip). Po uložení se soubor přesune do archives/<slug>/.', max_length=512, verbose_name='Soubor v /new'),
        ),
        migrations.AlterField(
            model_name='package',
            name='archive_file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_upload_path, validators=[api.models.validate_is_zip], verbose_name='ZIP Archiv (upload)'),
        ),
        migrations.AlterField(
            model_name='package',
            name='file_size',
            field=models.BigIntegerField(default=0, help_text='Velikost v bajtech — vyplňuje se automaticky.'),
        ),
    ]
